baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'Data Engineer Camp'
theme = "hugo-book"

# Book configuration
disablePathToLower = true
enableGitInfo = true

[markup]
[markup.goldmark.renderer]
  unsafe = true

[markup.tableOfContents]
  startLevel = 1

[menu]

[params]
  BookTheme = 'light'
  BookToC = true
  # BookFavicon = 'favicon.png'
  # BookLogo = 'logo.png'
  BookMenuBundle = '/menu'
  BookSection = 'docs'
